#!/usr/bin/env bash
# Install nginx on your web-01 server that listen on port 80
# A GET query to '/' must return a page that contains "Hello world!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello world!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
