#!/usr/bin/env bash

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx
sudo rm /etc/nginx/sites-enabled/default
sudo touch /etc/nginx/sites-available/hello
sudo ln -s /etc/nginx/sites-available/hello /etc/nginx/sites-enabled/
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/hello
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location / {
                # return 200 with "Hello World!" as response
                return 200 "Hello World!";
        }
}
