#!/usr/bin/env bash
# Set up Nginx to listen on port 80 for all active IPv4 IPs
sed -i 's/listen\s*80;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx

