#!/usr/bin/env bash
# Sript gives info on file (exists? empty? file and not dir?)

file="School"

if [ -e "$file" ]; then
echo "$file file exists"

if [ -s "$file" ]; then
	echo "$file file is not empty"
else
	echo"$file file is empty"
fi

if [ -f "$file" ]; then
	echo "$file is a regular file"
fi

else
	echo "$file file does not exists"
fi
